### ISSUE TITLE
mvp for Python

### ISSUE THREAD

**Issue by sreznick** [sreznick/codesearch#4]
Support following logic:

run indexing on Python sources in some directory
run query on string constant
supply results - just for strings, not for any text based entries

**Comment by Wizzerinus** [comment]
- [x] Update parser/lexer to incorporate features from newer Python versions
  - [x] Underscores in numeric literals (Python 3.6) - [PEP 515](https://peps.python.org/pep-0515/)
  - [x] Positional only arguments `def f(n, /, m):` (Python 3.8) - [PEP 570](https://peps.python.org/pep-0570/)
  - [x] Walrus operator `if (x := y)` (Python 3.8) - [PEP 572](https://peps.python.org/pep-0572/)
  - [x] Relaxed decorator syntax (Python 3.9) - [PEP 614](https://peps.python.org/pep-0614/)
  - Pattern matching (Python 3.10) - already worked before - [PEP 622](https://peps.python.org/pep-0622/)
  - [x] Parenthesized context managers (Python 3.10) - no PEP
  - [x] Exception groups (Python 3.11) - [PEP 654](https://peps.python.org/pep-0654/)
  - [x] Typing syntax (Python 3.12) - [PEP 695](https://peps.python.org/pep-0695/)
  - [ ] Nested fstrings (Python 3.12) - [PEP 701](https://peps.python.org/pep-0701/)
- [x] run query on string constant and supply results - just for strings, not for any text based entries
- [ ] lucene work
  - [x] save metadata and string literals into lucene index
  - [x] pull string literals from lucene index instead of from disk
  - [ ] check if the index needs to be invalidated
    - implemented, but does not work
  - [ ] delete documents from index when respective file is deleted
